name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: 开始构建工作
    runs-on: macos-11
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: wy414012/MacKernelSDK
          path: MacKernelSDK
      - name: CI 构建引导
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/wy414012/ocbuild/Yaming/ci-bootstrap.sh) && eval "$src" || exit 1
      - name: Lilu 依赖引导
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/wy414012/Lilu/yaming-network/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1

      - run: xcodebuild -jobs 1 -configuration Debug
      - run: xcodebuild -jobs 1 -configuration Release

      - name: 打包工作件并上传
        uses: actions/upload-artifact@v2
        with:
          name: WhateverGreen-build
          path: build/*/*.zip


