name: build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: xcode-latest
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: wy414012/MacKernelSDK
          path: MacKernelSDK
      - name: CI 构建引导
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/wy414012/ocbuild/Yaming/ci-bootstrap.sh) && eval "$src" || exit 1
      - name: Lilu 依赖引导
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/wy414012/Lilu/yaming-network/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - run: xcodebuild -jobs 1 -configuration Debug
      - run: xcodebuild -jobs 1 -configuration Release
      
      - name: 配置安全密钥
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GIT_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          
      - name: push Web server
        env:
          SECRET_CHECK_SCRIPT_URL: ${{ secrets.SECRET_CHECK_SCRIPT_URL }}
        run: scp -r ./build/*/*.zip ${SECRET_CHECK_SCRIPT_URL}OC/kext/
        
      - name: 打包工作件并上传
        uses: actions/upload-artifact@v3
        with:
          name: WhateverGreen-build
          path: build/*/*.zip
      - name: 上传发布版本
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true
